version: '3'
services:
  app:
    container_name: victor-bhub-api-project
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 80 --reload
    volumes:
      - .:/app
    ports:
      - "8000:80"